# Generated by Django 3.2.7 on 2021-09-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalapi', '0002_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
