# Generated by Django 3.2.7 on 2021-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalapi', '0004_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
