# Generated by Django 3.2.7 on 2021-09-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalapi', '0005_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
