# Generated by Django 3.2.7 on 2021-09-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalapi', '0006_rename_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
