# Generated by Django 3.2.7 on 2021-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalapi', '0008_auto_20210916_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
